
# This sets the syspath to include the local path, which allows access to the
# blueprints in the blueprints directory.
# http://stacker.readthedocs.io/en/latest/config.html#module-paths
sys_path: .

# The bucket where stacker stores generated CloudFormation templates.
# http://stacker.readthedocs.io/en/latest/config.html#s3-bucket
stacker_bucket: ${stacker_bucket}

namespace: ${namespace}

mappings:
  AmiMap:
    us-east-1:
      amazon: ami-c58c1dd3
    us-east-2:
      amazon: ami-4191b524
    us-west-2:
      amazon: ami-4836a428

general_parameters: &general_parameters
  BaseDomain: ${BaseDomain}
  InternalDomain: ${InternalDomain}

# The stacks key accepts a list of stack declarations.
# http://stacker.readthedocs.io/en/latest/config.html#stacks
stacks:
  # This is an example minimal stack.
  # The 'name' and 'class_path' keys are required.
  # The 'name' value must be unique.
  # The 'class_path' points at a Python stacker "blueprint" class.
  - name: s3-and-cloudfronttest
    class_path: blueprints.s3_and_cloudfront.s3_and_cloudfront
    description: This example blueprint will create an s3 bucket and a cloudfront distribution
    enabled: true
    variables:
      << : *general_parameters

  - name: s3-and-dynamo
    class_path: blueprints.s3_and_dynamo.s3_and_dynamo
    description: This example blueprint will create an s3 bucket and a dynamo table
    enabled: true
    variables:
      << : *general_parameters

 
